### ISSUE TITLE
New mails at the root of the inbox are not displayed if subfolders exists

### ISSUE THREAD

**Issue by motorradfahrer** [dersphere/plugin.programm.xbmcmail#2]
Again hi,

I have tested yesterday the mail addon for the first time and found an issue. The behavior is the same no matter if Kodi is used at Windows or OpenElec.

I use a GMX mailbox and have some folders at the inbox to archive mails which I want keep for a longer time. These folders and the mails inside can be oped without any issue. They are displayed as separate folders at your addon but there is no folder for the inbox itself which means I don't see any new incomming mail.

Perhaps it is easy to change for myself if you give me a hint what is required to do?

Thanks!

**Comment by dersphere** [comment]
Hi,

the Inbox in IMAP is a folder like all other folders so you should see it.
Could you send me your XBMC/Kodi log?
I only need the lines which contain "XBMCMailClient" - please have a look if there is any private data before sending it. You can find my email address in the addon.xml

**Comment by dersphere** [comment]
Thanks for your emails. I fixed the issue and will release a new version in the next days...
